# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tvanessa <tvanessa@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/11 21:11:52 by tvanessa          #+#    #+#              #
#    Updated: 2020/01/11 21:39:12 by tvanessa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

MOZZ_DIR = .mozz
VS_DIR = .vscode

all:
	git clone https://github.com/Mozzart88/21-c-debugger-vscode.git $(VS_DIR)
	rm -fr $(VS_DIR)/.git